name: muralhunt
description: Explore the city by capturing murals
publish_to: 'none'
version: 1.1.0+5

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  geolocator: ^11.0.0
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  animations: ^2.0.7
  gallery_saver: ^2.3.2
  maps_launcher: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo_red.png"
  min_sdk_android: 21

flutter:
  assets:
    - lib/assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/Rubik-VariableFont_wght.ttf
